// Code generated by go generate ./...; DO NOT EDIT
// Last generated on 07 Aug 21 12:09 UTC

// Package check provides types to perform checks on values
// in a testing context.
package check

import (
	"net/http"
	"time"
)

type (
	// BytesPassFunc is the required method to implement BytesPasser.
	// It returns a boolean that indicates whether the gotten []byte value
	// passes the current check.
	BytesPassFunc func(got []byte) bool
	// StringPassFunc is the required method to implement StringPasser.
	// It returns a boolean that indicates whether the gotten string value
	// passes the current check.
	StringPassFunc func(got string) bool
	// IntPassFunc is the required method to implement IntPasser.
	// It returns a boolean that indicates whether the gotten int value
	// passes the current check.
	IntPassFunc func(got int) bool
	// DurationPassFunc is the required method to implement DurationPasser.
	// It returns a boolean that indicates whether the gotten time.Duration value
	// passes the current check.
	DurationPassFunc func(got time.Duration) bool
	// HTTPHeaderPassFunc is the required method to implement HTTPHeaderPasser.
	// It returns a boolean that indicates whether the gotten http.Header value
	// passes the current check.
	HTTPHeaderPassFunc func(got http.Header) bool
	// UntypedPassFunc is the required method to implement UntypedPasser.
	// It returns a boolean that indicates whether the gotten interface{} value
	// passes the current check.
	UntypedPassFunc func(got interface{}) bool

	// ExplainFunc is the required method to implement Explainer.
	// It returns a string explaining why the gotten value failed the check.
	// The label provides some context, such as "response code".
	ExplainFunc func(label string, got interface{}) string
)

type (
	// BytesPasser provides a method Pass that returns a bool that indicates
	// whether the gotten []byte value passes the current check.
	BytesPasser interface{ Pass(got []byte) bool }
	// StringPasser provides a method Pass that returns a bool that indicates
	// whether the gotten string value passes the current check.
	StringPasser interface{ Pass(got string) bool }
	// IntPasser provides a method Pass that returns a bool that indicates
	// whether the gotten int value passes the current check.
	IntPasser interface{ Pass(got int) bool }
	// DurationPasser provides a method Pass that returns a bool that indicates
	// whether the gotten time.Duration value passes the current check.
	DurationPasser interface{ Pass(got time.Duration) bool }
	// HTTPHeaderPasser provides a method Pass that returns a bool that indicates
	// whether the gotten http.Header value passes the current check.
	HTTPHeaderPasser interface{ Pass(got http.Header) bool }
	// UntypedPasser provides a method Pass that returns a bool that indicates
	// whether the gotten interface{} value passes the current check.
	UntypedPasser interface{ Pass(got interface{}) bool }

	// Explainer provides a method Explain describing the reason of a failed check.
	Explainer interface {
		Explain(label string, got interface{}) string
	}
)

type (
	// BytesChecker implements both BytesPasser and Explainer interfaces.
	BytesChecker interface {
		BytesPasser
		Explainer
	}
	// StringChecker implements both StringPasser and Explainer interfaces.
	StringChecker interface {
		StringPasser
		Explainer
	}
	// IntChecker implements both IntPasser and Explainer interfaces.
	IntChecker interface {
		IntPasser
		Explainer
	}
	// DurationChecker implements both DurationPasser and Explainer interfaces.
	DurationChecker interface {
		DurationPasser
		Explainer
	}
	// HTTPHeaderChecker implements both HTTPHeaderPasser and Explainer interfaces.
	HTTPHeaderChecker interface {
		HTTPHeaderPasser
		Explainer
	}
	// UntypedChecker implements both UntypedPasser and Explainer interfaces.
	UntypedChecker interface {
		UntypedPasser
		Explainer
	}
)

// bytesCheck is an implementation of BytesChecker interface
type bytesCheck struct {
	passFunc BytesPassFunc
	explFunc ExplainFunc
}

// Pass returns a boolean that indicates whether the gotten []byte value
// passes the current check.
func (c bytesCheck) Pass(got []byte) bool { return c.passFunc(got) }

// Explain explains the reason of a failed check for the gotten value.
func (c bytesCheck) Explain(label string, got interface{}) string { return c.explFunc(label, got) }

// NewBytesCheck returns a custom BytesChecker with the provided BytesPassFunc
// and ExplainFunc.
func NewBytesCheck(passFunc BytesPassFunc, explainFunc ExplainFunc) BytesChecker {
	return bytesCheck{passFunc: passFunc, explFunc: explainFunc}
}

// stringCheck is an implementation of StringChecker interface
type stringCheck struct {
	passFunc StringPassFunc
	explFunc ExplainFunc
}

// Pass returns a boolean that indicates whether the gotten string value
// passes the current check.
func (c stringCheck) Pass(got string) bool { return c.passFunc(got) }

// Explain explains the reason of a failed check for the gotten value.
func (c stringCheck) Explain(label string, got interface{}) string { return c.explFunc(label, got) }

// NewStringCheck returns a custom StringChecker with the provided StringPassFunc
// and ExplainFunc.
func NewStringCheck(passFunc StringPassFunc, explainFunc ExplainFunc) StringChecker {
	return stringCheck{passFunc: passFunc, explFunc: explainFunc}
}

// intCheck is an implementation of IntChecker interface
type intCheck struct {
	passFunc IntPassFunc
	explFunc ExplainFunc
}

// Pass returns a boolean that indicates whether the gotten int value
// passes the current check.
func (c intCheck) Pass(got int) bool { return c.passFunc(got) }

// Explain explains the reason of a failed check for the gotten value.
func (c intCheck) Explain(label string, got interface{}) string { return c.explFunc(label, got) }

// NewIntCheck returns a custom IntChecker with the provided IntPassFunc
// and ExplainFunc.
func NewIntCheck(passFunc IntPassFunc, explainFunc ExplainFunc) IntChecker {
	return intCheck{passFunc: passFunc, explFunc: explainFunc}
}

// durationCheck is an implementation of DurationChecker interface
type durationCheck struct {
	passFunc DurationPassFunc
	explFunc ExplainFunc
}

// Pass returns a boolean that indicates whether the gotten time.Duration value
// passes the current check.
func (c durationCheck) Pass(got time.Duration) bool { return c.passFunc(got) }

// Explain explains the reason of a failed check for the gotten value.
func (c durationCheck) Explain(label string, got interface{}) string { return c.explFunc(label, got) }

// NewDurationCheck returns a custom DurationChecker with the provided DurationPassFunc
// and ExplainFunc.
func NewDurationCheck(passFunc DurationPassFunc, explainFunc ExplainFunc) DurationChecker {
	return durationCheck{passFunc: passFunc, explFunc: explainFunc}
}

// httpHeaderCheck is an implementation of HTTPHeaderChecker interface
type httpHeaderCheck struct {
	passFunc HTTPHeaderPassFunc
	explFunc ExplainFunc
}

// Pass returns a boolean that indicates whether the gotten http.Header value
// passes the current check.
func (c httpHeaderCheck) Pass(got http.Header) bool { return c.passFunc(got) }

// Explain explains the reason of a failed check for the gotten value.
func (c httpHeaderCheck) Explain(label string, got interface{}) string { return c.explFunc(label, got) }

// NewHTTPHeaderCheck returns a custom HTTPHeaderChecker with the provided HTTPHeaderPassFunc
// and ExplainFunc.
func NewHTTPHeaderCheck(passFunc HTTPHeaderPassFunc, explainFunc ExplainFunc) HTTPHeaderChecker {
	return httpHeaderCheck{passFunc: passFunc, explFunc: explainFunc}
}

// untypedCheck is an implementation of UntypedChecker interface
type untypedCheck struct {
	passFunc UntypedPassFunc
	explFunc ExplainFunc
}

// Pass returns a boolean that indicates whether the gotten interface{} value
// passes the current check.
func (c untypedCheck) Pass(got interface{}) bool { return c.passFunc(got) }

// Explain explains the reason of a failed check for the gotten value.
func (c untypedCheck) Explain(label string, got interface{}) string { return c.explFunc(label, got) }

// NewUntypedCheck returns a custom UntypedChecker with the provided UntypedPassFunc
// and ExplainFunc.
func NewUntypedCheck(passFunc UntypedPassFunc, explainFunc ExplainFunc) UntypedChecker {
	return untypedCheck{passFunc: passFunc, explFunc: explainFunc}
}
