// Code generated by go generate ./...; DO NOT EDIT
// Last generated on 03 Sep 21 20:01 UTC

package check

import (
	"regexp"
	"time"
)

type (
	// BoolCheckerProvider provides checks on type bool.
	BoolCheckerProvider interface {
		// Is checks the gotten bool is equal to the target.
		Is(tar bool) BoolChecker
	}

	// BytesCheckerProvider provides checks on type []byte.
	BytesCheckerProvider interface {
		// Is checks the gotten []byte is equal to the target.
		Is(tar []byte) BytesChecker
		// Len checks the gotten []byte's length passes the provided
		// IntChecker.
		Len(c IntChecker) BytesChecker
		// Not checks the gotten []byte is not equal to the target.
		Not(values ...[]byte) BytesChecker
		// SameJSON checks the gotten []byte and the target returns
		// the same JSON object.
		SameJSON(tar []byte) BytesChecker
	}

	// DurationCheckerProvider provides checks on type time.Duration.
	DurationCheckerProvider interface {
		// Over checks the gotten time.Duration is over the target duration.
		Over(tar time.Duration) DurationChecker
		// Under checks the gotten time.Duration is under the target duration.
		Under(tar time.Duration) DurationChecker
	}

	// HTTPHeaderCheckerProvider provides checks on type http.Header.
	HTTPHeaderCheckerProvider interface {
		// KeyNotSet checks the gotten http.Header does not have
		// a specific key set.
		KeyNotSet(key string) HTTPHeaderChecker
		// KeySet checks the gotten http.Header has a spcific key set.
		// The corresponding value is ignored, meaning an empty value
		// for that key passes the check.
		KeySet(key string) HTTPHeaderChecker
		// ValueNotSet checks the gotten http.Header does not have
		// any key with a matching value.
		ValueNotSet(val string) HTTPHeaderChecker
		// ValueOf checks the gotten http.Header has a value
		// for the matching key that passes the given StringChecker.
		ValueOf(key string, c StringChecker) HTTPHeaderChecker
		// ValueSet checks the gotten http.Heaser has any key
		// witha a matching value.
		ValueSet(val string) HTTPHeaderChecker
	}

	// IntCheckerProvider provides checks on type int.
	IntCheckerProvider interface {
		// GT checks the gotten int is greater than the target.
		GT(tar int) IntChecker
		// GTE checks the gotten int is greater or equal to the target.
		GTE(tar int) IntChecker
		// InRange checks the gotten int is in the closed interval [lo:hi].
		InRange(lo, hi int) IntChecker
		// Is checks the gotten int is equal to the target.
		Is(tar int) IntChecker
		// LT checks the gotten int is lesser than the target.
		LT(tar int) IntChecker
		// LTE checks the gotten int is lesser or equal to the target.
		LTE(tar int) IntChecker
		// Not checks the gotten int is not equal to the target.
		Not(values ...int) IntChecker
		// OutRange checks the gotten int is not in the closed interval [lo:hi].
		OutRange(lo, hi int) IntChecker
	}

	// StringCheckerProvider provides checks on type string.
	StringCheckerProvider interface {
		// Contains checks the gotten string contains the target substring.
		Contains(sub string) StringChecker
		// Is checks the gotten string is equal to the target.
		Is(tar string) StringChecker
		// Len checks the gotten string's length passes the given IntChecker.
		Len(c IntChecker) StringChecker
		// Match checks the gotten string matches the given regexp.
		Match(rgx *regexp.Regexp) StringChecker
		// Not checks the gotten string is not equal to the target.
		Not(values ...string) StringChecker
		// NotContains checks the gotten string do not contain the target
		// substring.
		NotContains(sub string) StringChecker
		// NotMatch checks the gotten string do not match the given regexp.
		NotMatch(rgx *regexp.Regexp) StringChecker
	}

	// StructCheckerProvider provides checks on type interface{}.
	StructCheckerProvider interface {
		// FieldsEqual checks all given fields pass the ValueChecker.
		// It panics if the fields do not exist or are not exported,
		// or if the tested value is not a struct.
		CheckFields(c ValueChecker, fields []string) ValueChecker
		// FieldsEqual checks all given fields equal the exp value.
		// It panics if the fields do not exist or are not exported,
		// or if the tested value is not a struct.
		FieldsEqual(exp interface{}, fields []string) ValueChecker
		// IsZero checks the gotten struct only contains zero values,
		// meaning it has not been initialized.
		IsZero() ValueChecker
		// NotZero checks the gotten struct contains at least 1 non-zero value,
		// meaning it has been initialized.
		NotZero() ValueChecker
		// SameJSON checks the gotten struct and the target value
		// result in the same JSON.
		// It panics if any error occurs in the marshaling process.
		SameJSON(tar interface{}) ValueChecker
	}

	// ValueCheckerProvider provides checks on type interface{}.
	ValueCheckerProvider interface {
		// Custom checks the gotten value passes the given ValuePassFunc.
		// The description should typically begin with keywords like "expect"
		// or "should" for intelligible output.
		// For instance, "expect odd number" would output:
		// 	> "expect odd number, got 42"
		Custom(desc string, f ValuePassFunc) ValueChecker
		// Is checks the gotten value is equal to the target.
		Is(tar interface{}) ValueChecker
		// Not checks the gotten value is not equal to the target.
		Not(values ...interface{}) ValueChecker
	}
)

var (
	// Bool implements BoolCheckerProvider.
	Bool BoolCheckerProvider = boolCheckerProvider{}
	// Bytes implements BytesCheckerProvider.
	Bytes BytesCheckerProvider = bytesCheckerProvider{}
	// Duration implements DurationCheckerProvider.
	Duration DurationCheckerProvider = durationCheckerProvider{}
	// HTTPHeader implements HTTPHeaderCheckerProvider.
	HTTPHeader HTTPHeaderCheckerProvider = httpHeaderCheckerProvider{}
	// Int implements IntCheckerProvider.
	Int IntCheckerProvider = intCheckerProvider{}
	// String implements StringCheckerProvider.
	String StringCheckerProvider = stringCheckerProvider{}
	// Struct implements StructCheckerProvider.
	Struct StructCheckerProvider = structCheckerProvider{}
	// Value implements ValueCheckerProvider.
	Value ValueCheckerProvider = valueCheckerProvider{}
)
