version: 2.1

jobs:
  build:
    working_directory: ~/testx
    docker:
      - image: circleci/golang:1.16.5
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Set up environment
          command: |
            git config --global url."ssh://git@github.com".insteadOf "https://github.com"
            go env -w GOPRIVATE="github.com/drykit-go/*"
            go mod download
            go get -v golang.org/x/tools/cmd/goimports

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Run code gen
          command: |
            make gen

      - run:
          name: Run linters
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.40.1
            make lint

      - run:
          name: Run unit tests
          command: |
            go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - run:
          name: Send test coverage results
          command: |
            bash <(curl -s https://codecov.io/bash)
